// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SMT.Back.Comissoes.Data;

#nullable disable

namespace SMT.Back.Comissoes.Migrations
{
    [DbContext(typeof(DbContextClass))]
    [Migration("20260204065634_atualizandoUsuario")]
    partial class atualizandoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AtivoParaServicos")
                        .HasColumnType("boolean");

                    b.Property<double>("Avaliacao")
                        .HasColumnType("double precision");

                    b.Property<string>("Estilo")
                        .HasColumnType("text");

                    b.Property<string>("TipoArtista")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.Interacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlvoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TipoAlvoInteracao")
                        .HasColumnType("integer");

                    b.Property<int>("TipoInteracao")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "AlvoId", "TipoAlvoInteracao", "TipoInteracao")
                        .IsUnique();

                    b.ToTable("Interacao");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.PortfolioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Hashtags")
                        .HasColumnType("text[]");

                    b.Property<int>("QuantidadeCurtidas")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeSalvos")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeVisualizacoes")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.ToTable("PortfolioItem");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.PortfolioItemImagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("PortfolioItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioItemId");

                    b.ToTable("PortfolioItemImagem");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.RedeSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RedeSocial");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.Servicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("TermosDeServicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("TermosDeServicoId");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.ServicosImagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServicosId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServicosId");

                    b.ToTable("ServicosImagem");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.TermoDeServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistaId")
                        .HasColumnType("integer");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TermoDeServico");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<int?>("Celular")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstiloDescricao")
                        .HasColumnType("text");

                    b.Property<string>("FotoCapa")
                        .HasColumnType("text");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("text");

                    b.Property<bool>("JaAnunciou")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomePerfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.PortfolioItem", b =>
                {
                    b.HasOne("SMT.Back.Comissoes.Models.Entity.Artista", null)
                        .WithMany("PortfolioItens")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.PortfolioItemImagem", b =>
                {
                    b.HasOne("SMT.Back.Comissoes.Models.Entity.PortfolioItem", null)
                        .WithMany("Imagens")
                        .HasForeignKey("PortfolioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.RedeSocial", b =>
                {
                    b.HasOne("SMT.Back.Comissoes.Models.Entity.Usuario", null)
                        .WithMany("RedesSociais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.Servicos", b =>
                {
                    b.HasOne("SMT.Back.Comissoes.Models.Entity.Artista", null)
                        .WithMany("Servicos")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMT.Back.Comissoes.Models.Entity.TermoDeServico", "TermosDeServico")
                        .WithMany()
                        .HasForeignKey("TermosDeServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TermosDeServico");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.ServicosImagem", b =>
                {
                    b.HasOne("SMT.Back.Comissoes.Models.Entity.Servicos", null)
                        .WithMany("ServicosImages")
                        .HasForeignKey("ServicosId");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.Artista", b =>
                {
                    b.Navigation("PortfolioItens");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.PortfolioItem", b =>
                {
                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.Servicos", b =>
                {
                    b.Navigation("ServicosImages");
                });

            modelBuilder.Entity("SMT.Back.Comissoes.Models.Entity.Usuario", b =>
                {
                    b.Navigation("RedesSociais");
                });
#pragma warning restore 612, 618
        }
    }
}
